; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Printing Service"
#define MyAppVersion "0.1.1"
#define MyAppPublisher "Pronesoft SRL"
#define MyAppURL "https://pronesoft.com/"
#define MyAppExeName "printing-service.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{782CD44E-D687-4BDE-8782-392712B4C0F5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Pronesoft Printing Service
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PrintingServiceInstaller
Compression=lzma
SolidCompression=yes
WizardStyle=modern
AlwaysRestart=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\..\target\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\target\release\PDFtoPrinter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\target\release\win.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: {sys}\sc.exe; Parameters: "create PronesoftPrintingService start= auto binPath= ""{app}\win.exe""" ; Flags: runhidden

[UninstallRun]
Filename: {sys}\sc.exe; Parameters: "stop PronesoftPrintingService" ; Flags: runhidden
Filename: {sys}\sc.exe; Parameters: "delete PronesoftPrintingService" ; Flags: runhidden
